# Generated by Django 5.1.2 on 2024-10-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sport', 'Sport'), ('sleep', 'Sleep'), ('work', 'Work'), ('leisure', 'Leisure')], default='leisure', max_length=50),
        ),
    ]
